"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "dpps",
      [
        {
          name: "Sukijan",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Pramuka",
          tps_id: 1,
          caleg_id: 1,
          religion: "Islam",
          job: "PNS",
          image_national_card: "https://picsum.photos/200",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Darsono",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Kelinci",
          tps_id: 2,
          caleg_id: 2,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/201",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sudarso",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Duren",
          tps_id: 1,
          caleg_id: 1,
          religion: "Islam",
          job: "Wiraswasta",
          image_national_card: "https://picsum.photos/202",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Permadi",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Kucing",
          tps_id: 2,
          caleg_id: 2,
          religion: "Kristen",
          job: "Buruh",
          image_national_card: "https://picsum.photos/203",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Agung",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Anggur",
          tps_id: 2,
          caleg_id: 2,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/204",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Andhika",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Sungai",
          tps_id: 2,
          caleg_id: 2,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/205",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Darsini",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Kelinci",
          tps_id: 2,
          caleg_id: 2,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/206",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pujini",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Karang Bolong",
          tps_id: 2,
          caleg_id: 2,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/207",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Oktaviani",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Karang Tengah",
          tps_id: 3,
          caleg_id: 3,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/208",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Oktavianto",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Karang Selatan",
          tps_id: 3,
          caleg_id: 3,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/209",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Zahra",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Karang Timur",
          tps_id: 3,
          caleg_id: 3,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/210",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Xavier",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Sarijadi",
          tps_id: 4,
          caleg_id: 4,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/211",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Wahyu",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Pajajaran",
          tps_id: 4,
          caleg_id: 4,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/212",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Eka",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Yos Sudarso",
          tps_id: 4,
          caleg_id: 4,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/213",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Citra",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Haji Muhidin",
          tps_id: 4,
          caleg_id: 4,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/214",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Ayu",
          national_id: "1234567890123456",
          dob: "1990-01-01",
          address: "Jl. Sarijadi",
          tps_id: 4,
          caleg_id: 4,
          religion: "Islam",
          job: "Buruh",
          image_national_card: "https://picsum.photos/207",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("dpps", null, {});
  },
};
