"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "Tps",
      [
        {
          name: "Tps 01",

          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",

          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",

          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 19",
          desa_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 19",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 20",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 21",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 22",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 23",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 24",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 25",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 26",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 27",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 28",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 29",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 30",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 31",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 32",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 33",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 34",
          desa_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 19",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 20",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 21",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 22",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 23",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 24",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 25",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 26",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 27",
          desa_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 19",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 20",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 21",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 22",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 23",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 24",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 25",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 26",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 27",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 28",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 29",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 30",
          desa_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 18",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 19",
          desa_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 13",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 14",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 15",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 16",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 17",
          desa_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 01",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 02",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 03",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 04",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 05",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 06",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 07",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 08",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 09",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 10",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 11",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tps 12",
          desa_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("Tps", null, {});
  },
};
